[build]
  # Build command (not needed for static site, but keeping for future use)
  command = "echo 'Building static site'"
  
  # Directory to publish
  publish = "."
  
  # Environment variables (these will be set in Netlify dashboard)
  # VITE_SUPABASE_URL = "https://your-project-ref.supabase.co"
  # VITE_SUPABASE_ANON_KEY = "your-anon-key"

[build.environment]
  # Node version (if needed for build processes)
  NODE_VERSION = "18"

# Redirect rules for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and CORS
[[headers]]
  for = "/*"
  [headers.values]
    # Basic security headers
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Content Security Policy (adjust as needed)
    Content-Security-Policy = '''
      default-src 'self';
      script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdn.tailwindcss.com https://cdnjs.cloudflare.com https://esm.sh;
      style-src 'self' 'unsafe-inline' https://cdn.tailwindcss.com;
      img-src 'self' data: https: blob:;
      font-src 'self' https: data:;
      connect-src 'self' https://api.jikan.moe https://*.supabase.co wss://*.supabase.co;
      media-src 'self' https:;
      object-src 'none';
      base-uri 'self';
      form-action 'self';
    '''

# Cache static assets
[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.jpeg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Progressive Web App support
[[headers]]
  for = "/manifest.json"
  [headers.values]
    Content-Type = "application/manifest+json"
    Cache-Control = "public, max-age=86400"
